---

- name: include OS specific variables
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- debug: var=mafalb.mysql
  tags:
    - never
    - debug

- name: assertitions
  assert:
    that:
      - mafalb.mysql.server.manage_package
      - mafalb.mysql.server.package is defined
      - mafalb.mysql.server.additional_packages is defined

- name: package is present
  when: mafalb.mysql.server.manage_package
  package:
    name: "{{ [ mafalb.mysql.server.package ] + mafalb.mysql.server.additional_packages }}"
    state: present

- name: my.cnf is in place
  when:
    - mafalb.mysql.server.manage_config
    - not mafalb.mysql.server.external_config
  template:
    src: server.cnf
    dest: "{{ mafalb.mysql.server.mysqld_cnf }}"
  notify: reload mysql

- name: my.cnf is in place
  when:
    - mafalb.mysql.server.manage_config
    - mafalb.mysql.server.external_config
  template:
    src: server.cnf
    dest: "{{ mafalb.mysql.server.mysqld_cnf }}"
  notify: reload mysql

- name: mysql daemon is running
  service:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  register: mysql_is_running
