---

- name: include OS specific variables
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- debug: var=mafalb.mysql
  tags:
    - never
    - debug

- name: package is present
  when: mafalb.mysql.server.manage_package
  package:
    name: "{{ [ mafalb.mysql.server.package ] + mafalb.mysql.server.additional_packages }}"
    state: present

- name: my.cnf is in place
  when: mafalb.mysql.server.manage_config
  template:
    src: "{{ my.cnf }}"
    dest: "{{ mysql_cnf }}"
  notify: reload mysql

- name: mysql daemon is running
  service:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  register: mysql_is_running
