---

- debug: var=mysql
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - mysql.type is defined

- name: include OS specific variables
  include_vars: types.yml

- name: include OS specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: assertions
  assert:
    that:
      - mysql.server.manage_package
      - mysql.server.package is defined
      - mysql.server.additional_packages is defined

- name: package is present
  when: mysql.server.manage_package
  package:
    name: "{{ [ mysql.server.package ] + mysql.server.additional_packages }}"
    state: present

- name: my.cnf is in place
  when:
    - mysql.server.manage_config
    - not mysql.server.external_config
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    backup: true
  notify: reload mysql

- name: my.cnf is in place
  when:
    - mysql.server.manage_config
    - mysql.server.external_config
  template:
    src: my.cnf
    dest: /etc/my.cnf
  notify: reload mysql

- name: mysql service is running
  service:
    name: "{{ mysql.server.service }}"
    state: started
    enabled: true
  register: mysql_is_running

- name: installation is secured
  include_tasks: secure.yml
