---

- name: package is present
  when: mafalb.mysql.server.manage_package
  package:
    name: "{{ mafalb.mysql.server.package }}"
    state: present
  
- name: additional packages are installed
  package:
    name: MySQL-python

- name: my.cnf is in place
  when: mafalb.mysql.server.manage_config
  template:
    src: "{{ my.cnf }}"
    dest: "{{ mysql_cnf }}"
  notify: reload mysql

- name: mysql daemon is running
  service:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  register: mysql_is_running
