# vim: set ft=yaml ts=2 expandtab:
---
- name: assertions
  assert:
    that: (mysql_dump_sftp_server is defined) or (mysql_dump_local_dest is defined)

- name: lz4 is installed
  package:
    name: lz4
    state: present

- name: mysql backup script is present
  template:
    src: backup.mysql.sh.j2
    dest: /usr/local/sbin/backup.mysql
    mode: 00755

- name: symlink to daily cronjobs is present
  file:
    src: /usr/local/sbin/backup.mysql
    dest: /etc/cron.daily/backup.mysql
    state: link

- block:

    - name: script for hardlinking is present on sftp server
      copy:
        src: hardlink
        dest: /usr/local/sbin/
        mode: 00755

    - name: cronjob is present
      cron:
        name: hardlink backups for user {{ ansible_hostname }}backup
        job: "/usr/local/sbin/hardlink /home/{{ ansible_hostname }}backup/Documents/mysql"
        hour: '5'
        minute: '55'
        user: root
        backup: true

  delegate_to: "{{ mysql_dump_sftp_server }}"
  when: mysql_dump_sftp_server is defined

      
...
